### ISSUE TITLE
Jersey forbids multiple components with the same class

### ISSUE THREAD

**Issue by timothyjward** [geckoprojects-org/org.gecko.jaxrs.whiteboard#18]
It is common in OSGi for components to use the multi-ton pattern where factory configurations create multiple instances. This is useful for creating JAX-RS interceptors with different roles. Unfortunately Jersey forbids two extension instances with the same class to be registered (even though this isn't part of the JAX-RS specification). Gecko will therefore have to create a proxy class for each extension which implements the contract interfaces. This will force Jersey to see each extension as a separate item.

**Comment by maho7791** [comment]
fixed with PR #19
