### ISSUE TITLE
Application selection filter is String+

### ISSUE THREAD

**Issue by timothyjward** [geckoprojects-org/org.gecko.jaxrs.whiteboard#35]
This code fails when provided with a String[] or List<String>, both of which are valid according to the spec.

https://github.com/geckoprojects-org/org.gecko.jaxrs.whiteboard/blob/jakarta/org.gecko.rest.jersey/src/org/gecko/rest/jersey/runtime/application/JerseyApplicationContentProvider.java#L210

**Comment by maho7791** [comment]
https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.jaxrs.html#service.jaxrs.common.properties
https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.jaxrs.html#org.osgi.service.jaxrs.whiteboard.propertytypes.JaxrsApplicationSelect

Extension select is String+, or am I wrong?

**Comment by timothyjward** [comment]
The application select property was made String+ in the Jakarta update

https://osgi.github.io/osgi/cmpn/service.jakartars.html#service.jakartars.common.properties

**Comment by maho7791** [comment]
Uhhhh :-), then we need a TCK test for that?

**Comment by maho7791** [comment]
fixed
