### ISSUE TITLE
Unwanted javax.servlet dependency in the OptionalResponseFilter

### ISSUE THREAD

**Issue by timothyjward** [geckoprojects-org/org.gecko.jaxrs.whiteboard#36]
https://github.com/geckoprojects-org/org.gecko.jaxrs.whiteboard/blob/jakarta/org.gecko.rest.jersey/src/org/gecko/rest/jersey/util/OptionalResponseFilter.java#L60

This constant should come from the `jakarta.ws.rs.Response.Status` class surely? If not then it should at least come from the `jakarta.servlet` package, not `javax.servlet`.

**Comment by maho7791** [comment]
Absolutely
